[package]
name = "mortar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
normalize-path = "0.2.1"
rayon = "1.7.0"
regex = "1.9.4"
starlark = "0.9.0"
walkdir = "2.3.3"

[lib]
